FROM node:21-alpine3.18 
WORKDIR /app 
COPY package*.json ./
COPY tsconfig.json ./
COPY .npmrc ./ 
RUN npm install && npm install -g nodemon
COPY src ./src 
RUN ls -a
EXPOSE 4002
CMD ["npm", "run", "dev"]